---
title: "Robust BMARS Output"
author: "Andy Shen"
date: "7/31/2020"
output: pdf_document
---

# Data Initialization

```{r}
rm(list = ls())
set.seed(12)
source("robust_bmars2.R")
```



```{r}
f <-function(x){
  10*sin(pi*x[,1]*x[,2])+20*(x[,3]-.5)^2+10*x[,4]+5*x[,5]
}

sigma <- 1 # noise sd
n <- 500 # number of observations
x <- matrix(runif(n*10),n,10) #10 variables, only first 5 matter
y <- rnorm(n,f(x),sigma) #+ rnorm(n)
```

## Adding Arbitrary Extreme Outliers

```{r}
index <- sample(n, 20)
y[index] <- y[index] + rnorm(index, 0, 15)
```

\pagebreak

# Running the Model

```{r}
nmcmc <- 3000
mod <- bmars(x, its = nmcmc, nu = 5, verbose = TRUE)
```

# Results

```{r}
X <- mod$X
beta <- mod$beta
mod$count
mod$nknot[length(mod$nknot)]
tail(mod$nknot, 25)
tail(mod$mat_beta[,1:(mod$nknot[length(mod$nknot)]+1)])
as.vector(beta)
```

\pagebreak

# Plots

```{r}
plot(mod$nknot, type = "l",
     main = "Number of knots over time") 

# plot(mod$alpha, type = "l",
#      main = "alpha^2 values over time")

plot(mod$mat_sig, type = "l",
     main = "Sigma^2 values over time")

plot(mod$lam, type = "l",
     main = "Lambda values over time")

# matplot(mod$mat_beta, type = "l",
#         main = "Plot of regression coefficients over time")

matplot(sqrt(mod$mat_w[seq(nmcmc/2,nmcmc,by=2),]), type="l",
        main = "Plot of v_i values over time")

hist(colMeans((mod$mat_w[seq(nmcmc/2,nmcmc,by=2),])))

# matplot(sqrt(mod$mat_u), type="l",
#         main = "Plot of u_i values over time")

plot(X %*% beta, y,
main = "Bayesian predicted values vs actual y values")
points((X %*% beta)[index],y[index],col="red")
abline(0, 1, lwd = 5, col = "blue1") #should follow a very straight line

mod1 <- lm(y ~ X %*% beta); rsq <- summary(mod1)$r.squared
cat("The predicted y values are correlated with the actual values with 
an R^2 of", rsq, "\n")
a<-(y-(X %*% (mod$mat_beta)[nrow(mod$mat_beta),(1:(mod$nknot[nmcmc]+1))]))
plot(a,type="l")
var(a[-index])
plot(mod$alpha,type="l")
plot(mod$mat_tau2,type="l")
```

```{r}
tail(mod$mat_sig)
tail(sqrt(mod$mat_w[,1:25]))
var((y-(X%*%beta)))
var(y)
```

